In [1]:
import numpy as np
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()

In [3]:
# iris

In [4]:
x = iris.data

In [5]:
y = iris.target

In [8]:
from keras.utils import to_categorical

In [9]:
y = to_categorical(y)

In [10]:
y.shape

(150, 3)

In [11]:
# y

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size = 0.33, random_state = 42)

In [14]:
from sklearn.preprocessing import MinMaxScaler

In [15]:
scaler_object = MinMaxScaler()

In [16]:
scaler_object.fit(X_train)

MinMaxScaler()

In [17]:
scaled_X_train = scaler_object.transform(X_train)
scaled_X_test = scaler_object.transform(X_test)

In [18]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [19]:
model = Sequential()
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(3,activation='softmax'))
model.compile(loss = 'categorical_crossentropy',optimizer = 'adam',metrics=['accuracy'])

In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 40        
                                                                 
 dense_1 (Dense)             (None, 8)                 72        
                                                                 
 dense_2 (Dense)             (None, 3)                 27        
                                                                 
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [21]:
model.fit(scaled_X_train,y_train,epochs = 150, verbose = 2)

Epoch 1/150
4/4 - 1s - loss: 1.0722 - accuracy: 0.3400 - 914ms/epoch - 229ms/step
Epoch 2/150
4/4 - 0s - loss: 1.0673 - accuracy: 0.3400 - 15ms/epoch - 4ms/step
Epoch 3/150
4/4 - 0s - loss: 1.0626 - accuracy: 0.3400 - 13ms/epoch - 3ms/step
Epoch 4/150
4/4 - 0s - loss: 1.0591 - accuracy: 0.3500 - 14ms/epoch - 3ms/step
Epoch 5/150
4/4 - 0s - loss: 1.0549 - accuracy: 0.3500 - 13ms/epoch - 3ms/step
Epoch 6/150
4/4 - 0s - loss: 1.0512 - accuracy: 0.3900 - 12ms/epoch - 3ms/step
Epoch 7/150
4/4 - 0s - loss: 1.0476 - accuracy: 0.4700 - 12ms/epoch - 3ms/step
Epoch 8/150
4/4 - 0s - loss: 1.0440 - accuracy: 0.4600 - 12ms/epoch - 3ms/step
Epoch 9/150
4/4 - 0s - loss: 1.0405 - accuracy: 0.4500 - 13ms/epoch - 3ms/step
Epoch 10/150
4/4 - 0s - loss: 1.0369 - accuracy: 0.4600 - 16ms/epoch - 4ms/step
Epoch 11/150
4/4 - 0s - loss: 1.0332 - accuracy: 0.4800 - 12ms/epoch - 3ms/step
Epoch 12/150
4/4 - 0s - loss: 1.0294 - accuracy: 0.4900 - 12ms/epoch - 3ms/step
Epoch 13/150
4/4 - 0s - loss: 1.0255 - accurac

In [25]:
predict = model.predict(scaled_X_test)

2/2 [==============================] - 0s 9ms/step


In [26]:
classes = np.argmax(predict,axis = 1)

In [27]:
classes

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [29]:
test = np.argmax(y_test,axis=1)

In [30]:
test

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [32]:
count = 0
for i in range(len(test)):
  if(test[i] == classes[i]):
    count = count + 1;
accuracy = count/len(test)

In [34]:
accuracy*100

98.0

In [35]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [36]:
confusion_matrix(test,classes)

array([[19,  0,  0],
       [ 0, 14,  1],
       [ 0,  0, 16]])

In [37]:
print(classification_report(test,classes))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.93      0.97        15
           2       0.94      1.00      0.97        16

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50



In [38]:
print(accuracy_score(test,classes))

0.98
